# Generated by Django 6.0.4 on 2026-04-14 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock_non_negative'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWED', 'Revisada')], db_index=True, default='PENDING', max_length=10, verbose_name='estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to='suppliers.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'solicitud de pedido',
                'verbose_name_plural': 'solicitudes de pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='cantidad a pedir')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='notas')),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.orderrequest', verbose_name='solicitud de pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'ítem de solicitud',
                'verbose_name_plural': 'ítems de solicitud',
            },
        ),
    ]
