# Generated by Django 6.0.4 on 2026-04-13 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería')], max_length=3, verbose_name='tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='número de documento')),
                ('position', models.CharField(max_length=100, verbose_name='cargo')),
                ('hire_date', models.DateField(verbose_name='fecha de contratación')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='salario base')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='inicio del período')),
                ('period_end', models.DateField(verbose_name='fin del período')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('PAID', 'Pagada')], db_index=True, default='DRAFT', max_length=10, verbose_name='estado')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls_generated', to=settings.AUTH_USER_MODEL, verbose_name='generada por')),
            ],
            options={
                'verbose_name': 'nómina',
                'verbose_name_plural': 'nóminas',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='salario base')),
                ('health_deduction', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='descuento salud')),
                ('pension_deduction', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='descuento pensión')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='horas extras')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='salario neto')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='employees.employee', verbose_name='empleado')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees.payroll', verbose_name='nómina')),
            ],
            options={
                'verbose_name': 'ítem de nómina',
                'verbose_name_plural': 'ítems de nómina',
                'unique_together': {('payroll', 'employee')},
            },
        ),
    ]
