# Generated by Django 6.0.4 on 2026-04-13 04:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='document_number',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='número de documento'),
        ),
    ]
