# Generated by Django 6.0.4 on 2026-04-14 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_encrypt_document_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='inicio de semana (lunes)')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='employees.employee', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'horario laboral',
                'verbose_name_plural': 'horarios laborales',
                'ordering': ['-week_start', 'employee__full_name'],
                'unique_together': {('employee', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], db_index=True, verbose_name='día de la semana')),
                ('start_time', models.TimeField(verbose_name='hora de entrada')),
                ('end_time', models.TimeField(verbose_name='hora de salida')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.workschedule', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['day_of_week'],
                'unique_together': {('schedule', 'day_of_week')},
            },
        ),
    ]
