# Generated by Django 6.0.4 on 2026-04-14 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_encrypt_document_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='descripción')),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio sugerido; puede ajustarse al registrar el servicio.', max_digits=12, null=True, verbose_name='precio base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipo de servicio',
                'verbose_name_plural': 'tipos de servicio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio')),
                ('service_date', models.DateField(db_index=True, verbose_name='fecha del servicio')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='customers.customer', verbose_name='cliente')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_performed', to=settings.AUTH_USER_MODEL, verbose_name='realizado por')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_registered', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicetype', verbose_name='tipo de servicio')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
