# Generated by Django 6.0.4 on 2026-04-13 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de factura')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='impuesto')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de emisión')),
                ('sent_by_email', models.BooleanField(default=False, verbose_name='enviada por correo')),
                ('status', models.CharField(choices=[('ISSUED', 'Emitida'), ('CANCELLED', 'Anulada')], db_index=True, default='ISSUED', max_length=10, verbose_name='estado')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='cliente')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_generated', to=settings.AUTH_USER_MODEL, verbose_name='generada por')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'factura de cliente',
                'verbose_name_plural': 'facturas de cliente',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_invoice_number', models.CharField(max_length=50, verbose_name='número de factura del proveedor')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('received_at', models.DateField(db_index=True, verbose_name='fecha de recepción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='suppliers.purchaseorder', verbose_name='orden de compra')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices_registered', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='suppliers.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'factura de proveedor',
                'verbose_name_plural': 'facturas de proveedor',
                'ordering': ['-received_at'],
                'unique_together': {('supplier', 'supplier_invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.supplierinvoice', verbose_name='factura de proveedor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'ítem de factura de proveedor',
                'verbose_name_plural': 'ítems de factura de proveedor',
            },
        ),
    ]
