# Generated by Django 6.0.4 on 2026-04-13 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Visualizar')], db_index=True, max_length=6, verbose_name='acción')),
                ('app_label', models.CharField(max_length=50, verbose_name='aplicación')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='modelo')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID del objeto')),
                ('object_repr', models.CharField(max_length=200, verbose_name='representación del objeto')),
                ('changed_fields', models.JSONField(blank=True, help_text='Formato: {"campo": {"old": valor_anterior, "new": valor_nuevo}}', null=True, verbose_name='campos modificados')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
