# Generated by Django 6.0.4 on 2026-04-13 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto de apertura')),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto de cierre')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto esperado')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='diferencia')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], db_index=True, default='OPEN', max_length=6, verbose_name='estado')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_registers', to=settings.AUTH_USER_MODEL, verbose_name='cerrada por')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_registers', to=settings.AUTH_USER_MODEL, verbose_name='abierta por')),
            ],
            options={
                'verbose_name': 'caja',
                'verbose_name_plural': 'cajas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso')], db_index=True, max_length=7, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('concept', models.CharField(max_length=255, verbose_name='concepto')),
                ('reference_type', models.CharField(choices=[('SALE', 'Venta'), ('SUPPLIER_INVOICE', 'Factura de proveedor'), ('PAYROLL', 'Nómina'), ('OTHER', 'Otro')], max_length=20, verbose_name='tipo de referencia')),
                ('reference_id', models.IntegerField(help_text='PK del objeto relacionado (venta, factura, nómina, etc.)', verbose_name='ID de referencia')),
                ('transaction_date', models.DateField(db_index=True, verbose_name='fecha de transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_registered', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
